[build]
  base = "Frontend/vite-project"          # Replace "subfolder" with the actual path to your subfolder
  command = "npm run build"   # Adjust this to your build script
  publish = "Frontend/vite-project/dist"  # Adjust this to your Vite.js output directory within the subfolder
